CREATE USER c##firstproj IDENTIFIED BY firstproj;
GRANT dba TO c##firstproj

CREATE TABLE MEMBER(
CMS_ID VARCHAR2(20) PRIMARY KEY,
CMS_PWD VARCHAR2(20) NOT NULL,
NAME VARCHAR2(10) NOT NULL,
BIRTHDAY VARCHAR2(10) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL
);

SELECT * FROM MEMBER

CREATE TABLE CUSTOMER(
CSM_ID VARCHAR2(20) PRIMARY KEY,
RESERVATION VARCHAR2(10),
RES_DAY VARCHAR2(15),
RES_TIME VARCHAR2(10),
RES_PEOPLE VARCHAR2(10),
RES_MEMO VARCHAR2(100),
RES_REMEMO VARCHAR2(100)
)

SELECT * FROM CUSTOMER