CREATE USER c##firstproj IDENTIFIED BY firstproj;
GRANT dba TO c##firstproj

CREATE TABLE CUSTOMER(
CSM_ID VARCHAR2(20) PRIMARY KEY,
CSM_PD VARCHAR2(20) NOT NULL,
)

SELECT * FROM customer

ALTER TABLE customer ADD name varchar2(10) NOT NULL;
ALTER TABLE CUSTOMER ADD BIRTHDAY VARCHAR2(8) NOT NULL;
ALTER TABLE CUSTOMER ADD EMAIL VARCHAR2(30) NOT NULL;

ALTER TABLE CUSTOMER ADD RESERVATION VARCHAR2(10);
ALTER TABLE CUSTOMER ADD RES_DAY VARCHAR2(15);
ALTER TABLE CUSTOMER ADD RES_TIME VARCHAR2(10);
ALTER TABLE CUSTOMER ADD RES_PEOPLE VARCHAR2(10);
ALTER TABLE CUSTOMER ADD RES_MEMO VARCHAR2(100);
ALTER TABLE CUSTOMER ADD RES_REMEMO VARCHAR2(100);